<?php
/*=======================================================\
|                        FrontHrm                        |
|--------------------------------------------------------|
|                            |
|                                                        |
\=======================================================*/

include_once($path_to_root."/modules/FrontHrm/includes/db/employee_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/department_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/salary_scale_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/overtime_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/attendance_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/account_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/salary_structure_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/payslip_db.inc");
