<?php
/**********************************************************************
    
***********************************************************************/
/*
	This file contains templates for all country specific functions.
	If your locale needs special functionality provided by hook functions
	copy this file to respective lang/xx_XX directory and edit templates below.
	You can safely remove not used function templates.
	
	Name it after language code e.g. hooks_en_US
*/
class hooks_xx_XX extends hooks {
/*
	//
	
	
	
	//
	//	Returns: amount in words as string.
	
	function price_in_words($amount, $doc_type)
	{
	}
*/
/*
	//
	
	
	
	
	
	
	function retrieve_ex_rate($curr, $date)
	{
	 	$provider = 'ECB'; 
		return get_extern_rate($curr, $provider, $date);
	}
*/
/*
	
	
	
	//
	
	function tax_report_done()
	{
	}
*/
}
